[2024-02-16T00:33:01.286+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: twitter_collector.op_twitter manual__2024-02-16T00:33:00.151582+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
